### ISSUE TITLE
'fsleyes render' crashes when combining annotation with hidden canvas

### ISSUE THREAD

**Issue by davidrs06** [pauldmccarthy/fsleyes#104]
Hi !

I think `fsleyes render` doesn't consider the possibility to have hidden canvas when saving renderings with annotations.

The following command

    fsleyes render -of /tmp/test.png -xh -a /tmp/annotations.txt /tmp/test.nii.gz

gives the following error:

    Traceback (most recent call last):
      File "/usr/local/fsl/fslpython/envs/fslpython/bin/fsleyes", line 11, in <module>
        sys.exit(main())
      File "/usr/local/fsl/fslpython/envs/fslpython/lib/python3.8/site-packages/fsleyes/filtermain.py", line 210, in main
        result = fm.main(args)
      File "/usr/local/fsl/fslpython/envs/fslpython/lib/python3.8/site-packages/fsleyes/main.py", line 238, in main
        render.main(args[1:])
      File "/usr/local/fsl/fslpython/envs/fslpython/lib/python3.8/site-packages/fsleyes/render.py", line 93, in main
        bitmap, bg = render(
      File "/usr/local/fsl/fslpython/envs/fslpython/lib/python3.8/site-packages/fsleyes/render.py", line 375, in render
        saveannotations.loadAnnotations(MockOrthoPanel(canvases),
      File "/usr/local/fsl/fslpython/envs/fslpython/lib/python3.8/site-packages/fsleyes/plugins/tools/saveannotations.py", line 257, in loadAnnotations
        'Z' : ortho.getZCanvas().getAnnotations()}
      File "/usr/local/fsl/fslpython/envs/fslpython/lib/python3.8/site-packages/fsleyes/render.py", line 868, in getZCanvas
        return self.canvases[2]

Removing the `-xh` option saves the three canvas correctly. Calling just `fsleyes` instead of `fsleyes render -of /tmp/test.png` opens a display with only the y and z canvas, as expected, and is also able to take a screenshot from the GUI. However, after closing the window, the terminal freezes until hitting Ctrl-C.

Thanks for the amazing tool !

Best regards,
David

**Comment by pauldmccarthy** [comment]
Hi @davidrs06, the issue here is that your `annotations.txt` file contains annotations for canvases that are being hidden (hidden canvases are not created when using `fsleyes render`). 

I'll fix this in an upcoming FSLeyes release so that irrelevant annotations are ignored, but in the meantime, I would suggest using a modified `annotations.txt` file which does not contain annotations for canvases that are not being displayed.

**Comment by davidrs06** [comment]
Hi @pauldmccarthy, thanks for your comment !

Turns out I had an old version of fsleyes installed (v 1.3.0). I updated it to 1.5.0 using `$FSLDIR/fslpython/bin/conda update -n fslpython -c conda-forge --update-all fsleyes`, but still run into an error when running `fsleyes render -of /tmp/fsleyes_screenshot.png -xh -yh -a /tmp/annotation.txt --standard1mm`:

    Traceback (most recent call last):
      File "/usr/local/fsl/fslpython/envs/fslpython/bin/fsleyes", line 10, in <module>
        sys.exit(main())
      File "/usr/local/Software/fsl/fslpython/envs/fslpython/lib/python3.8/site-packages/fsleyes/filtermain.py", line 212, in main
        result = fm.main(args)
      File "/usr/local/Software/fsl/fslpython/envs/fslpython/lib/python3.8/site-packages/fsleyes/main.py", line 233, in main
        render.main(args[1:])
      File "/usr/local/Software/fsl/fslpython/envs/fslpython/lib/python3.8/site-packages/fsleyes/render.py", line 93, in main
        bitmap, bg = render(
      File "/usr/local/fsl/fslpython/envs/fslpython/lib/python3.8/site-packages/fsleyes/render.py", line 386, in render
        saveannotations.loadAnnotations(MockOrthoPanel(canvases),
      File "/usr/local/Software/fsl/fslpython/envs/fslpython/lib/python3.8/site-packages/fsleyes/plugins/tools/saveannotations.py", line 256, in loadAnnotations
        'Y' : ortho.getYCanvas().getAnnotations(),
      File "/usr/local/fsl/fslpython/envs/fslpython/lib/python3.8/site-packages/fsleyes/render.py", line 876, in getYCanvas
        return self.canvases[1]
    IndexError: list index out of range

The annotation file contains only a Z annotation, the content is: `Z TextAnnotation colour=#a00000 lineWidth=1 alpha=100.0 honourZLimits=False zmin=90.0 zmax=91.0 fontSize=27 coordinates=display text='Z Annotation' x=42.890774518593986 y=63.70973865465186`.

When looking closer, file `saveannotations.py` doesn't match the one on github, which seems to check for existing canvases. Do you know how I can sync my Fsleyes version with the latest gitHub or gitLab versions ? I'd really like to test it.

Best regards,
David

**Comment by pauldmccarthy** [comment]
Aah, there is a problem with my proposed work around I'm afraid. I've fixed the bug, but am hoping to get a few more changes in before releasing a new version. But you should be able to run a development version by doing this:

```
git clone https://git.fmrib.ox.ac.uk/fsl/fsleyes/fsleyes.git
export PYTHONPATH=$(pwd)/fsleyes
fsleyes ....
```

**Comment by davidrs06** [comment]
Looking forward for the new release then :)

Setting PYTHONPATH to the git repository doesn't do the trick for me unfortunately, the error still pops-out, pointing at files in /usr/local/fsl. Would you have an idea on how to point things to the git repo ? I'm on Ubuntu 22.04.1 LTS

**Comment by pauldmccarthy** [comment]
Could you try this instead, after setting `$PYTHONPATH`?

```
fslpython -m fsleyes ...
```

**Comment by pauldmccarthy** [comment]
Hi  @davidrs06, this should be fixed as of FSLeyes 1.6.0, apologies for the delay
