### ISSUE TITLE
Display issue for high DPI monitor

### ISSUE THREAD

**Issue by soichih** [pauldmccarthy/fsleyes#34]
My laptop (XPS13) has a high DPI resolution (3840x2160) pixels with 200% scaling. When I open fsleyes, it shows images in the right bottom corner of the screen.

![Screenshot from 2019-10-17 20-00-26](https://user-images.githubusercontent.com/923896/67056440-fc3f6400-f119-11e9-8ff2-d63dd924aa2c.png)

Do I need to do something special to make fsleyes working for high DPI monitor?

**Comment by pauldmccarthy** [comment]
I can reproduce this on my laptop (ubuntu 18.04, high DPI display). I pretty much exclusively run at 1x scale, because I find support for 2x scale is too poor in linux (e.g. when using external displays), so I hadn't noticed this before.

Anyway, this looks like a problem in wxwidgets: 
https://github.com/wxWidgets/Phoenix/issues/1327

I'll dig into it a bit further when I get a chance.

**Comment by pauldmccarthy** [comment]
I have been waiting for high DPI support (on platforms other than macOS) to be made available in wxpython - this is now the case (as of 4.0.7, I think), so I'll aim to update the fsleyes code in the next week or so.

**Comment by pauldmccarthy** [comment]
Apologies for the delay - this should be fixed in FSLeyes 0.32.1 (as long as you've also got a recent wxPython as well)

**Comment by soichih** [comment]
@pauldmccarthy Great thanks!

I just did apt upgrade fsleyes but I am still seeing 0.15.2 on Ubuntu18.

```
$ fsleyes --version
fsleyes/FSLeyes version 0.15.2
```

Do you know when the new version will be released to Ubuntu 18.04 apt repo?

**Comment by pauldmccarthy** [comment]
I have no idea I'm afraid - I am not responsible for the neurodebian releases. I only support the installation methods outlined here: https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/FSLeyes

(the standalone builds for the latest version are not ready yet - I will hopefully be able to get them out by tomorrow).

**Comment by pauldmccarthy** [comment]
This should be fixed in the latest version of FSLeyes - feel free to re-open if you still have trouble.

**Comment by pcasl** [comment]
Sorry, I just install the latest fsleyes on Mac, FSLeyes version: 0.33.2, but still the same problem. #54. Perhaps you can reopen the question?
